[package]
name = "msfs"
version = "0.0.0-pre.1"
authors = ["snek"]
edition = "2018"
description = "Rust bindings for the MSFS SDK"
license-file = "LICENSE"

[dependencies]
msfs_derive = { path = "../msfs_derive" }
futures = "0.3"

[build-dependencies]
bindgen = "0.55"
msfs_sdk = { path = "../msfs_sdk" }
